export const LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';