export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_FAILED = 'GET_ITEMS_FAILED';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';

export const POST_ITEM_REQUEST = 'POST_ITEM_REQUEST';
export const POST_ITEM_FAILED = 'POST_ITEM_FAILED';
export const POST_ITEM_SUCCESS = 'POST_ITEM_SUCCESS';

export const DELETE_ITEM_REQUEST = 'POST_ITEM_REQUEST';
export const DELETE_ITEM_FAILED = 'POST_ITEM_FAILED';
export const DELETE_ITEM_SUCCESS = 'POST_ITEM_SUCCESS';

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM_FAILED = 'UPDATE_ITEM_FAILED';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';